application: tactile-hold-89302
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
#- url: /images
#  static_dir: images 
  
- url: /Add/.*
  script: Add.app
- url: /upload/.*
  script: upload.app
- url: /edit
  script: edit.app
- url: /paper
  script: paper.app
- url: /.*
  script: Cloud.app
